package proxy

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"os/signal"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/git-treeline/cli/internal/registry"
)

// AliasSource returns static alias routes to merge into the route table.
// Registry routes take priority over aliases.
type AliasSource func() map[string]int

// Router is a subdomain-based reverse proxy that routes
// {project}-{branch}.localhost requests to the correct worktree port
// by reading allocations from the git-treeline registry.
type Router struct {
	listenPort   int
	registry     *registry.Registry
	routes       map[string]int
	mu           sync.RWMutex
	useTLS       bool
	baseDomain   string
	aliasSources []AliasSource
}

func NewRouter(listenPort int, reg *registry.Registry) *Router {
	r := &Router{
		listenPort: listenPort,
		registry:   reg,
		routes:     make(map[string]int),
		baseDomain: "localhost",
	}
	r.refreshRoutes()
	return r
}

// WithBaseDomain sets the local TLD used for subdomain extraction.
func (r *Router) WithBaseDomain(domain string) *Router {
	if domain != "" {
		r.baseDomain = domain
	}
	return r
}

// WithAliases adds an alias source that is merged on each route refresh.
// Call Refresh() after all builders to populate the route table immediately.
func (r *Router) WithAliases(src AliasSource) *Router {
	r.aliasSources = append(r.aliasSources, src)
	return r
}

// Refresh forces an immediate route table rebuild. Useful after calling
// builder methods (WithAliases, WithBaseDomain) to populate routes before
// Run() starts the periodic refresh ticker.
func (r *Router) Refresh() {
	r.refreshRoutes()
}

// WithTLS enables HTTPS using the local CA cert generated by gtl serve install.
func (r *Router) WithTLS() *Router {
	r.useTLS = true
	return r
}

// Run starts the router HTTP/HTTPS server and blocks until SIGINT/SIGTERM.
// Routes are refreshed from the registry every 5 seconds.
func (r *Router) Run() error {
	addr := fmt.Sprintf("127.0.0.1:%d", r.listenPort)
	server := &http.Server{
		Addr:              addr,
		Handler:           r,
		ReadHeaderTimeout: 10 * time.Second,
		ErrorLog:          log.New(io.Discard, "", 0),
	}

	ln, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("port %d is already in use", r.listenPort)
	}

	scheme := "http"
	if r.useTLS {
		cm, certErr := NewCertManager()
		if certErr != nil {
			_ = ln.Close()
			return fmt.Errorf("TLS setup failed: %w", certErr)
		}
		server.TLSConfig = &tls.Config{
			GetCertificate: cm.GetCertificate,
			MinVersion:     tls.VersionTLS12,
		}
		ln = tls.NewListener(ln, server.TLSConfig)
		scheme = "https"
	}

	r.refreshRoutes()

	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()
	go func() {
		for range ticker.C {
			r.refreshRoutes()
		}
	}()

	fmt.Printf("Router listening on %s://%s:%d\n", scheme, r.baseDomain, r.listenPort)
	r.printRoutes()
	fmt.Println("Press Ctrl+C to stop")

	errCh := make(chan error, 1)
	go func() {
		errCh <- server.Serve(ln)
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	select {
	case sig := <-quit:
		fmt.Printf("\nReceived %s, shutting down...\n", sig)
	case err := <-errCh:
		return err
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := server.Shutdown(ctx); err != nil {
		return fmt.Errorf("shutdown: %w", err)
	}

	fmt.Println("Router stopped.")
	return nil
}

const maxProxyHops = 5

func (r *Router) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	hops := 0
	if v := req.Header.Get("X-Gtl-Hops"); v != "" {
		hops, _ = strconv.Atoi(v)
	}
	if hops >= maxProxyHops {
		r.serveLoopDetected(w, hops)
		return
	}

	host := req.Host
	if idx := strings.LastIndex(host, ":"); idx != -1 {
		host = host[:idx]
	}

	subdomain := r.extractSubdomain(host)
	if subdomain == "" {
		r.serveStatusPage(w, req)
		return
	}

	r.mu.RLock()
	targetPort, ok := r.routes[subdomain]
	if !ok {
		if idx := strings.Index(subdomain, "."); idx != -1 {
			parent := subdomain[idx+1:]
			targetPort, ok = r.routes[parent]
		}
	}
	r.mu.RUnlock()

	if !ok {
		r.serveNotFound(w, subdomain)
		return
	}

	r.proxyTo(w, req, targetPort)
}

func (r *Router) proxyTo(w http.ResponseWriter, req *http.Request, targetPort int) {
	backendHost := resolveLocalhost(targetPort)
	target := &url.URL{
		Scheme: "http",
		Host:   fmt.Sprintf("%s:%d", backendHost, targetPort),
	}

	hops := 0
	if v := req.Header.Get("X-Gtl-Hops"); v != "" {
		hops, _ = strconv.Atoi(v)
	}

	proxy := &httputil.ReverseProxy{
		Rewrite: func(pr *httputil.ProxyRequest) {
			pr.SetURL(target)
			pr.Out.Header.Set("X-Forwarded-Host", pr.In.Host)
			pr.Out.Header.Set("X-Gtl-Hops", strconv.Itoa(hops+1))
			if pr.In.TLS != nil {
				pr.Out.Header.Set("X-Forwarded-Proto", "https")
			} else if pr.In.Header.Get("X-Forwarded-Proto") == "" {
				pr.Out.Header.Set("X-Forwarded-Proto", "http")
			}
			if pr.In.RemoteAddr != "" {
				pr.Out.Header.Set("X-Forwarded-For", pr.In.RemoteAddr)
			}
		},
	}
	proxy.ServeHTTP(w, req)
}

func (r *Router) refreshRoutes() {
	allocs := r.registry.Allocations()
	routes := make(map[string]int, len(allocs))

	// Aliases go first so registry routes can override them
	for _, src := range r.aliasSources {
		for name, port := range src() {
			routes[name] = port
		}
	}

	for _, a := range allocs {
		project := registry.GetString(a, "project")
		branch := registry.GetString(a, "branch")
		if project == "" {
			continue
		}
		ports := registry.ExtractPorts(a)
		if len(ports) == 0 {
			continue
		}
		key := RouteKey(project, branch)
		routes[key] = ports[0]
	}

	r.mu.Lock()
	r.routes = routes
	r.mu.Unlock()
}

// Routes returns a snapshot of the current route table.
func (r *Router) Routes() map[string]int {
	r.mu.RLock()
	defer r.mu.RUnlock()
	cp := make(map[string]int, len(r.routes))
	for k, v := range r.routes {
		cp[k] = v
	}
	return cp
}

func (r *Router) scheme() string {
	if r.useTLS {
		return "https"
	}
	return "http"
}

func (r *Router) printRoutes() {
	routes := r.Routes()
	if len(routes) == 0 {
		fmt.Println("No active routes (run gtl setup in a worktree)")
		return
	}
	keys := sortedKeys(routes)
	fmt.Printf("Active routes (%d):\n", len(keys))
	for _, k := range keys {
		fmt.Printf("  %s://%s.%s → :%d\n", r.scheme(), k, r.baseDomain, routes[k])
	}
}

func (r *Router) serveStatusPage(w http.ResponseWriter, _ *http.Request) {
	routes := r.Routes()
	w.Header().Set("Content-Type", "text/html; charset=utf-8")

	_, _ = fmt.Fprint(w, "<html><head><title>git-treeline router</title>")
	_, _ = fmt.Fprint(w, "<style>body{font-family:system-ui,sans-serif;max-width:600px;margin:40px auto;padding:0 20px;color:#333}a{color:#0969da}h1{font-size:1.4em}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:6px 12px;border-bottom:1px solid #eee}th{color:#666;font-weight:500}</style>")
	_, _ = fmt.Fprint(w, "</head><body>")
	_, _ = fmt.Fprint(w, "<h1>git-treeline router</h1>")

	if len(routes) == 0 {
		_, _ = fmt.Fprint(w, "<p>No active routes. Run <code>gtl setup</code> in a worktree.</p>")
	} else {
		_, _ = fmt.Fprint(w, "<table><tr><th>Route</th><th>Port</th></tr>")
		for _, k := range sortedKeys(routes) {
			href := fmt.Sprintf("%s://%s.%s", r.scheme(), k, r.baseDomain)
			_, _ = fmt.Fprintf(w, "<tr><td><a href=%q>%s</a></td><td>%d</td></tr>", href, k, routes[k])
		}
		_, _ = fmt.Fprint(w, "</table>")
	}
	_, _ = fmt.Fprint(w, "</body></html>")
}

func (r *Router) serveNotFound(w http.ResponseWriter, subdomain string) {
	routes := r.Routes()
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusNotFound)

	var body strings.Builder
	fmt.Fprintf(&body, "<p>No route matches <code>%s</code>.</p>", subdomain)
	if len(routes) > 0 {
		body.WriteString("<p>Available routes:</p><table><tr><th>Route</th><th>Port</th></tr>")
		for _, k := range sortedKeys(routes) {
			href := fmt.Sprintf("%s://%s.%s", r.scheme(), k, r.baseDomain)
			fmt.Fprintf(&body, "<tr><td><a href=%q>%s</a></td><td>%d</td></tr>", href, k, routes[k])
		}
		body.WriteString("</table>")
	} else {
		body.WriteString("<p>No active routes. Run <code>gtl setup</code> in a worktree to allocate one.</p>")
	}
	_, _ = fmt.Fprint(w, renderErrorPage(404, "Route Not Found", body.String()))
}

func (r *Router) serveLoopDetected(w http.ResponseWriter, hops int) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusLoopDetected)
	body := fmt.Sprintf(
		"<p>This request looped through the router <strong>%d times</strong> before being stopped.</p>"+
			"<p>Your dev server is proxying requests back through the gtl router. Common fixes:</p>"+
			"<ul>"+
			"<li>Vite: set <code>server.proxy['/api'].changeOrigin = true</code></li>"+
			"<li>webpack-dev-server: set <code>devServer.proxy['/api'].changeOrigin = true</code></li>"+
			"<li>Next.js rewrites: ensure the destination uses <code>http://localhost:PORT</code>, not the <code>.localhost</code> hostname</li>"+
			"</ul>", hops)
	_, _ = fmt.Fprint(w, renderErrorPage(508, "Loop Detected", body))
}

const errorPageCSS = `body{font-family:system-ui,sans-serif;max-width:640px;margin:40px auto;padding:0 20px;color:#333;background:#fff}` +
	`@media(prefers-color-scheme:dark){body{background:#1a1a1a;color:#ddd}a{color:#58a6ff}code{background:#2d2d2d}table{border-color:#333}td,th{border-color:#333}}` +
	`a{color:#0969da}code{background:#f0f0f0;padding:2px 6px;border-radius:3px;font-size:0.9em}` +
	`h1{font-size:1.3em}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:6px 12px;border-bottom:1px solid #eee}th{color:#888;font-weight:500}` +
	`ul{line-height:1.8}`

func renderErrorPage(status int, title, body string) string {
	return fmt.Sprintf(
		"<html><head><title>%d — %s</title><style>%s</style></head><body><h1>%d — %s</h1>%s</body></html>",
		status, title, errorPageCSS, status, title, body)
}

func (r *Router) extractSubdomain(host string) string {
	return extractSubdomainFor(host, r.baseDomain)
}

// extractSubdomainFor returns the subdomain portion of a host like
// "salt-main.localhost" → "salt-main". Returns "" for plain base domain.
func extractSubdomainFor(host, baseDomain string) string {
	host = strings.ToLower(host)
	base := strings.ToLower(baseDomain)
	if host == base || host == "127.0.0.1" || host == "::1" {
		return ""
	}
	suffix := "." + base
	if strings.HasSuffix(host, suffix) {
		return strings.TrimSuffix(host, suffix)
	}
	return ""
}

var branchPrefixRe = regexp.MustCompile(`^(feature|chore|bugfix|hotfix)/`)
var sanitizeRouteRe = regexp.MustCompile(`[^a-z0-9-]`)
var collapseDashRe = regexp.MustCompile(`-{2,}`)

// RouteKey derives a DNS-safe route key from a project name and branch.
// Exported so gtl setup can display the router URL.
func RouteKey(project, branch string) string {
	project = strings.ToLower(project)
	project = sanitizeRouteRe.ReplaceAllString(strings.ReplaceAll(project, "_", "-"), "")

	if branch == "" {
		return truncateDNSLabel(project)
	}

	branch = strings.ToLower(branch)
	branch = branchPrefixRe.ReplaceAllString(branch, "")
	branch = strings.ReplaceAll(branch, "/", "-")
	branch = strings.ReplaceAll(branch, "_", "-")
	branch = sanitizeRouteRe.ReplaceAllString(branch, "")
	branch = collapseDashRe.ReplaceAllString(branch, "-")
	branch = strings.Trim(branch, "-")

	return truncateDNSLabel(project + "-" + branch)
}

// BuildRouterURL returns the HTTPS router URL for a given project/branch
// when the router is active, or falls back to a plain localhost URL.
// Pass svcRunning and pfConfigured from service.IsRunning() and
// service.IsPortForwardConfigured() to keep this function testable.
func BuildRouterURL(port int, project, branch, domain string, routerPort int, svcRunning, pfConfigured bool) string {
	if branch != "" && svcRunning {
		routeKey := RouteKey(project, branch)
		if pfConfigured {
			return fmt.Sprintf("https://%s.%s", routeKey, domain)
		}
		return fmt.Sprintf("https://%s.%s:%d", routeKey, domain, routerPort)
	}
	return fmt.Sprintf("http://localhost:%d", port)
}

// BuildTunnelURL returns the tunnel URL for a given project/branch when
// a tunnel domain is configured, or an empty string if not applicable.
func BuildTunnelURL(project, branch, tunnelDomain string) string {
	if tunnelDomain == "" || branch == "" {
		return ""
	}
	return "https://" + RouteKey(project, branch) + "." + tunnelDomain
}

const maxDNSLabel = 63

func truncateDNSLabel(label string) string {
	if len(label) <= maxDNSLabel {
		return label
	}
	h := sha256.Sum256([]byte(label))
	suffix := hex.EncodeToString(h[:])[:6]
	prefix := label[:maxDNSLabel-7]
	prefix = strings.TrimRight(prefix, "-")
	return prefix + "-" + suffix
}

var localhostCache sync.Map // port (int) → localhostEntry

type localhostEntry struct {
	host    string
	expires time.Time
}

const localhostCacheTTL = 5 * time.Second

// resolveLocalhost checks whether a port is reachable on IPv4 (127.0.0.1)
// or IPv6 (::1) and returns the appropriate address. Results are cached for
// localhostCacheTTL to avoid probing on every proxied request.
func resolveLocalhost(port int) string {
	if v, ok := localhostCache.Load(port); ok {
		if e := v.(localhostEntry); time.Now().Before(e.expires) {
			return e.host
		}
	}
	host := probeLocalhost(port)
	localhostCache.Store(port, localhostEntry{host: host, expires: time.Now().Add(localhostCacheTTL)})
	return host
}

func probeLocalhost(port int) string {
	for _, host := range []string{"127.0.0.1", "::1"} {
		addr := net.JoinHostPort(host, fmt.Sprintf("%d", port))
		conn, err := net.DialTimeout("tcp", addr, 500*time.Millisecond)
		if err == nil {
			_ = conn.Close()
			return host
		}
	}
	return "127.0.0.1"
}

func sortedKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
